Allows public.data types to be shared on iOS
meedan/react-native-share-menu pull request #69
Opened 2020-08-07 13:25 UTC by himmelarthur

First of all thanks for this great lib!

I need to be able to share pdf files on iOS from Safari without having to download the file; it's visibly packaged in a `NSProvider` conforming to the `kUTTypePDF` (`com.adobe.pdf`) file type. Instead of adding a handler for PDF files, I have added a handler for all kind of data (some sort of "catch all"), letting the user filter out the file extensions they want to be shared in the Share Extension's `Info.plist`.

Let me know if I missed anything, it is my very first time working with iOS and Swift 😄 
Thanks!

2020-08-07 14:14 UTC, Gustash commented
Hey, thanks for the PR! I will take a look at it soon, and I'll also look into if these changes would apply to the normal ShareViewController as well

2020-08-11 08:11 UTC, Gustash requested changes

2020-08-11 08:11 UTC, Gustash commented on ios/Modules/ShareMenuReactView.swift
> +                let url: URL! = item as? String
```suggestion
                let url: URL! = item as? URL
```

2020-08-11 08:12 UTC, Gustash commented on ios/Modules/ShareMenuReactView.swift
> +                let url: URL! = item as? String
@himmelarthur, can you fix this cast so that this PR can be merged? Thanks for this btw

2020-08-11 08:34 UTC, himmelarthur commented
@Gustash done! I'll let you merge the PR. Let me know if you need anything to make a new release :)

2020-08-11 08:53 UTC, Gustash approved these changes

2020-08-11 08:53 UTC, Gustash commented
@caiosba can you merge this and make a new patch release please?

2020-08-11 16:11 UTC, merged

2020-08-11 16:15 UTC, caiosba commented
Thanks, released v.5.0.1 with this!